### ISSUE TITLE
Allow getting decoding error info from find_and_decode_from_ functions.

### ISSUE THREAD

**Issue by kittyhacker101** [WanzenBug/rqrr#1]
Being able to access the decoding errors can be very useful for some use cases, and both the ```find_and_decode_from_func``` and ```find_and_decode_from_image``` functions don't allow you to see decoding errors, only successfully decoded QR codes. Passing through a ```Vec<DeQRResult>``` instead of a ```Vec<Code>``` will allow more flexibility without complicating the API much.

**Comment by WanzenBug** [comment]
Thank you for creating this issue!

I have some improvements lined up, mostly related to the default workflow. 

I want to make the more powerful usage more accessible, thus reducing the need for the mentioned functions.

Hopefully I will find time tomorrow to take a closer look.

**Comment by WanzenBug** [comment]
I've pushed a new beta version, where I removed a lot of these API's. The API is a compromise between more powerful and easy-to-use. The README has the new minimal example. I may have gone a bit too far into flexible API thing ;-).

I would appreciate some feedback.

**Comment by kittyhacker101** [comment]
The new API looks good, thanks for fixing this!
