### ISSUE TITLE
Strange ECC-Level

### ISSUE THREAD

**Issue by DRRDietrich** [WanzenBug/rqrr#11]
I generated a QR code for each ECC level and verified the ECC level [manually](https://qrcode.meetheed.com/question17.php). If I let `rqrr` output the meta data of the QR codes, the ECC levels are strange.

| ECC-Level of QR code | Output |
| -------------- | ---------  |
| L (0)       | ecc_level:1       |
| M (1)   | ecc_level:0        |
| Q (2)   | ecc_level:3        |
| H (3)   | ecc_level:2        |

The problem affects the example itself. The example QR code tests/data/github.gif has the ECC code M, but is recognized as 0.
```rust
assert_eq!(meta.ecc_level, 0);
```

**Comment by WanzenBug** [comment]
That's according to spec. L is not encoded as 0 but 1, etc. I could add an enum to avoid this confusion...

**Comment by DRRDietrich** [comment]
Many thanks! Then that is wrongly or at least unfavorably defined in `qrcode`? 
[https://github.com/kennytm/qrcode-rust/blob/master/src/types.rs#L98](https://github.com/kennytm/qrcode-rust/blob/master/src/types.rs#L98)

**Comment by WanzenBug** [comment]
It's not really wrong. Just that the values are interpreted differently. See https://github.com/kennytm/qrcode-rust/blob/faa4397ba7c5f441cb9a2b436c1e84a0d52ae942/src/canvas.rs#L1555 i.e. the 1 bit is flipped, which makes the level <-> number mapping more natural. As I said, switching this crate to an enum would probably avoid the confusion :shrug:

**Comment by DRRDietrich** [comment]
Okay, thanks! :)
