### ISSUE TITLE
Document `Grid.bounds` coordinate order

### ISSUE THREAD

**Issue by jonahkagan** [WanzenBug/rqrr#17]
The current documentation for `bounds` reads:

> bounds: [[Point](https://docs.rs/rqrr/latest/rqrr/struct.Point.html); [4](https://doc.rust-lang.org/nightly/std/primitive.array.html)]
The bounds of the square, in underlying coordinates.
If this grid references for example an underlying image, these values will be set to coordinates in that image.

It's not clear which point in the array corresponds to which coordinate of the image.

From reading the [code](https://github.com/WanzenBug/rqrr/blob/564f9cc68e4c957e60e9d80ff1596d35753fccb5/src/prepare.rs#L220-L225), it looks like the order is: top-left, top-right, bottom-right, bottom-left. Is that correct?

I'm happy to make a PR to add this to the docs if that would be helpful!

**Comment by WanzenBug** [comment]
Sure, feel free to create a PR
