### ISSUE TITLE
Panics when preparing invalid grids with low resolution

### ISSUE THREAD

**Issue by danya02** [WanzenBug/rqrr#3]
As mentioned in https://github.com/WanzenBug/rqrr/issues/2#issuecomment-663900640 sometimes the library will panic from one of the branches of [src/prepare.rs:307](https://github.com/WanzenBug/rqrr/blob/505c281db1fe4c7d30e3be595ec5a48b2cedebde/src/prepare.rs#L307). I haven't explored this thoroughly, but it seems to happen when dealing with invalid grids where the size of each module is close to a pixel -- an anecdotal example is that a grid that caused this problem stopped doing so when it was scaled up 8x.

Is there anything we can do about this? Maybe make `get_pixel_at_point` return an `Option<PixelColor>`, or add a null color to `PixelColor`? When the calling code gets a null result it can try to inspect pixels around this one to try and get the color, or if this pixel is absolutely essential it can propagate the error upwards to user code.

**Comment by intendednull** [comment]
Also running into this problem. Happens sometimes when image is low res or blurry.

**Comment by WanzenBug** [comment]
Fixed by treating out-of-bounds pixels as the same "color" as the nearest valid pixel.
