### ISSUE TITLE
Depends on outdated lru

### ISSUE THREAD

**Issue by RalfJung** [WanzenBug/rqrr#5]
While working on making rustc detect misuses of uninitialized memory (https://github.com/rust-lang/rust/pull/71274), this crate was flagged as a possible regression. The reason likely is that it depends on an old buggy version of lru (0.1); the latest version (0.6) should not be affected by this problem any more. It would be great if you could update. :)

**Comment by WanzenBug** [comment]
Hey! Thanks for bringing this to my attention. I took the opportunity to update all dependencies,, including `lru` to 0.6.

**Comment by RalfJung** [comment]
Thanks for the quick fix!
